# Generated by Django 2.0.7 on 2019-08-09 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wpisy', '0002_auto_20190808_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strzelanie',
            name='strzelec',
            field=models.CharField(choices=[('G', 'Gracjan'), ('K', 'Konrad'), ('W', 'Wąż'), ('B', 'Bestia')], max_length=1),
        ),
        migrations.DeleteModel(
            name='Zawodnik',
        ),
    ]
