# Generated by Django 2.0.7 on 2019-08-09 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wpisy', '0004_auto_20190809_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='strzelanie',
            name='rodzaj_tarczy',
            field=models.CharField(choices=[('Ł', 'Łatwa'), ('Ś', 'Średnia'), ('T', 'Trudna')], default='Łatwa', max_length=1),
        ),
    ]
