# Generated by Django 2.0.7 on 2019-08-09 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wpisy', '0005_strzelanie_rodzaj_tarczy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strzelanie',
            name='rodzaj_tarczy',
            field=models.CharField(choices=[('Ł', 'Łatwa'), ('Ś', 'Średnia'), ('T', 'Trudna')], default='Trudna', max_length=1),
        ),
    ]
