# Generated by Django 2.0.7 on 2019-08-09 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wpisy', '0006_auto_20190809_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strzelanie',
            name='opis',
            field=models.TextField(default='Nihil novi'),
        ),
    ]
