# Generated by Django 2.0.7 on 2019-08-12 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wpisy', '0009_auto_20190810_2250'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wpis',
            options={},
        ),
        migrations.RenameField(
            model_name='wpis',
            old_name='tytul',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='wpis',
            name='data',
        ),
        migrations.AddField(
            model_name='wpis',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
