# Generated by Django 2.0.7 on 2019-08-13 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wpisy', '0012_auto_20190814_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wpis',
            name='strzelec',
            field=models.CharField(choices=[('G', 'Gracjan'), ('K', 'Konrad'), ('W', 'Wąż'), ('B', 'Bestia'), ('J', 'Jagoda'), ('R', 'Rafał')], max_length=1),
        ),
    ]
