# Generated by Django 2.0.7 on 2019-08-15 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wpisy', '0013_auto_20190814_0157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wpis',
            name='rodzaj_tarczy',
        ),
        migrations.AlterField(
            model_name='wpis',
            name='strzelec',
            field=models.CharField(choices=[('Gracjan', 'Gracjan'), ('Konrad', 'Konrad'), ('Wąż', 'Wąż'), ('Bestia', 'Bestia'), ('Jagoda', 'Jagoda'), ('Rafał', 'Rafał')], max_length=15),
        ),
    ]
