# Generated by Django 2.0.7 on 2019-08-15 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wpisy', '0014_auto_20190815_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wpis',
            name='opis',
            field=models.TextField(default='Nihil novi', max_length=15),
        ),
        migrations.AlterField(
            model_name='wpis',
            name='published_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wpis',
            name='strzelec',
            field=models.CharField(choices=[('Gracjan', 'Gracjan'), ('Konrad', 'Konrad'), ('Grynia', 'Grynia'), ('Bestia', 'Bestia'), ('Jagoda', 'Jagoda'), ('Rafał', 'Rafał')], max_length=15),
        ),
    ]
