# Generated by Django 2.0.7 on 2019-08-17 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wpisy', '0015_auto_20190815_2147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wpis',
            name='title',
        ),
    ]
