# Generated by Django 2.0.7 on 2019-08-31 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wpisy', '0018_wpis_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wpis',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
