# Generated by Django 2.0.7 on 2019-08-31 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wpisy', '0019_auto_20190831_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wpis',
            name='title',
            field=models.CharField(default='post', max_length=20),
        ),
    ]
