# Generated by Django 2.0.7 on 2019-08-31 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wpisy', '0020_auto_20190831_0212'),
    ]

    operations = [
        migrations.CreateModel(
            name='WpisTTT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strzelec', models.CharField(choices=[('Gracjan', 'Gracjan'), ('Konrad', 'Konrad'), ('Grynia', 'Grynia'), ('Bestia', 'Bestia'), ('Jagoda', 'Jagoda'), ('Hampyl', 'Hampyl')], max_length=15)),
                ('punkty', models.IntegerField(default=10)),
                ('oddane_strzaly', models.IntegerField()),
                ('dystans', models.IntegerField(default=10)),
                ('published_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='wpis',
            name='title',
        ),
    ]
