# Generated by Django 2.0.7 on 2019-08-31 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wpisy', '0021_auto_20190831_0225'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WpisTTT',
        ),
    ]
