# Generated by Django 2.0.7 on 2019-09-01 21:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wpisy', '0024_remove_wpis_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='wpis',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
